require("harpoon").setup({})
local mark = require("harpoon.mark")
local ui = require("harpoon.ui")
vim.keymap.set("n", "<leader>a", mark.add_file, { desc = "harpoon: [a]dd file to mark list" })
vim.keymap.set("n", "<C-e>", ui.toggle_quick_menu, { desc = "harpoon: toggle quick menu" })
vim.keymap.set("n", "<C-i>", function()
	ui.nav_file(1)
end, { desc = "harpoon: navigate to file 1 in mark list" })
vim.keymap.set("n", "<C-t>", function()
	ui.nav_file(2)
end, { desc = "harpoon: navigate to file 2 in mark list" })
